### ISSUE TITLE
More slots for Save opened, Open Saved Editors

### ISSUE THREAD

**Issue by dmagician** [eamodio/vscode-restore-editors#3] opened 2017-03-06 00:39 UTC
re: "eamodio 3/3/2017 Would you mind creating an issue on GitHub for this request with some more details on what you'd like something like that to behave?"

Actually I don't know how exactly the VSC api works so I'm thinking about 2 ways how ti could be used.

1. If for example your commands can have parameter, then it could be behave like this:

Save Opened Editors Projectname
Open Saved Editors Projectname

2. If not possible to have parameters with comamands, then the simplest solution would be to duplicate the hardwired commands and have e.g. 3 save slots (still better than one)

Save Opened Editors1
Open Saved Editors1

Save Opened Editors2
Open Saved Editors2

Save Opened Editors3
Open Saved Editors3

If it was done like this. It would have one advantage over "1.". It would allow to have custom keyboard binding for every save/open pair. (I'm new to VSC, so I don't know much about keyboard binding, I have just somehow managed to bind save and open on F6/CTRL+F6. ;-)

------

As I said in review. I like what you did there, I was scanning plugins for something capable of doing something like this, and found nothing. Thank you for doing this.

**Comment by eamodio** [comment] 2017-03-06 01:46
@dmagician Thanks for the review and opening this issue! 

Currently the "save slot" that is used is per-folder (e.g. project) -- so you don't have to worry about saving the state in one project and it affecting another.

From the options available, I'm thinking that having a few well know slots is probably the way to go. While I think it is possible to bind commands with arbitrary arguments now (in code v1.10), I feel like it will be harder to use and you'd really want something with more UI to deal with it appropriately (like I did with [Save All the Tabs](https://github.com/eamodio/SaveAllTheTabs) for Visual Studio).

I will look into adding something like this into an upcoming version, but just fyi I am also somewhat hesitant to add too much into this extension at this point, because of how limited it is (because of the vscode api - there is so many things I can't re-open and even finding what is open is extremely fuzzy). I'm hopeful that later versions of the vscode api will offer a supported way to get access to the information I need.

**Comment by dmagician** [comment] 2017-03-06 07:45
WOW!!! You are right, I didn't know it works like that. Then it's totally perfect, it just needs to be better explained in the info about this plugin. Just tested, it works!! Thank you! ;-)

**Comment by eamodio** [comment] 2017-03-06 21:27
@dmagician thanks -- I'll update the readme with some more details about that

**Comment by dmagician** [comment] 2017-03-13 09:03
Is it possible that if I do git pull on the directory that had previously saved editors, the saved editors state will disappear? I somehow can't restore editors now. 

Maybe that feature with having specific named slots for saving isn't that bad idea at all.

**Comment by eamodio** [comment] 2017-03-13 13:05
@dmagician I can't see how those two things could be related, but please let me know if you that is a behavior you can reproduce.

**Comment by dmagician** [comment] 2017-03-13 14:20
Ok I will try to observe what leads to loss of saved editors.

**Comment by williscool** [comment] 2017-05-24 20:21
I'd prefer if the saves were just named and you could cycle through them.

For instance if you switch branches in git in the same project and some of the files dont exist on other branches

**Comment by eamodio** [comment] 2017-05-24 21:12
Just to let everyone here know, that while I am all for extending the functionality here and PRs are certainly very welcome, I've just been hesitant to add too much to it because of the hackery and caveats required by the current implementation. Once vscode adds support for https://github.com/Microsoft/vscode/issues/15178 I will be happy to put more features into it :)

Eventually I could see it come close in functionality (albeit with different UI) as my VS "proper" extension [Save All the Tabs](https://marketplace.visualstudio.com/items?itemName=EricAmodio.SaveAlltheTabs)

**Comment by eamodio** [comment] 2023-04-09 03:25
Resolved in 1.0

**Closed as completed by eamodio** 2023-04-09 03:25 UTC
Labels: feature
